# NumPy
NumPy is the most basic package for using Python to do scientific computing. It is the foundation for most of the other scientific libraries. The ndarray is the heart of this library (N-Dimensional Array). This notebook is mostly about the data structure ndarray.

In [2]:
# It is a convention to import numpy as 'np'
import numpy as np

# ndarray
There are several differences between a Python list and a NumPy ndarray.

ndarray is homogenous which means that a single array can contain elements of a specific type only.
NumPy stores data in a contiguous block of memory, independent of any Python object.
NumPy is implemented in C, has less overhead, and uses less memory.
Fast vectorized operations, usually 10 to 100 times faster than normal Python loops.
# Initializing ndarray
 array() — Takes a Python list, ndarray, or any sequence-like object and returns a new ndarray. It creates a copy of the given data.

asarray() — Similar to array(), but it does not create a copy if the input is already an ndarray. Instead, it returns a reference to the same memory.

arange() — Works like Python’s built-in range() function. It generates evenly spaced numbers within a given interval.

dtype parameter — NumPy automatically detects the best data type for the array, but you can manually set it using the dtype argument.

In [3]:
array1d = np.array([1, 2, 3.5, 4, 5])
array2d = np.asarray([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], dtype=np.float32)
array = np.arange(10, dtype=np.int16)

print('array1d (vector)\n', array1d)
print('array2d (matrix)\n', array2d)
print('array\n', array)

array1d (vector)
 [1.  2.  3.5 4.  5. ]
array2d (matrix)
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
array
 [0 1 2 3 4 5 6 7 8 9]


The key difference between array() and asarray() when creating a new ndarray is that if the input is already an ndarray, asarray() returns a reference to the existing data instead of making a new copy.

In [4]:
array_2 = np.array(array) #Always creates new array, Creates Copy
array_3 = np.asarray(array) #Reuses existing array, Shares Memory

# array_3 was constructed using the np.asarray function. Since the
# input array was already a ndarray, np.asarray just assigned the memory
# location of the input to array_3 variable. That's why array and array_3
# have same memory address. But, array_2 has different one because it was
# created using np.array function and it always copies the input and returns
# a fresh array.
print(id(array))
print(id(array_2))
print(id(array_3))

136546284625168
136546286123312
136546284625168


In [5]:
# now, if we change anything in array_3, it will be also reflected on array
# as both share the same memory location. That's why we should avoid asarray.
array_3[0] = 1000
print('array3\n', array_3)
print('array\n', array)


array3
 [1000    1    2    3    4    5    6    7    8    9]
array
 [1000    1    2    3    4    5    6    7    8    9]


We can measure how long it takes to perform an operation on a Python list and a NumPy ndarray using the %timeit command. This command calculates the execution time of any given expression. In this example, we compare the time required to square all elements in a Python list and a NumPy array, each containing 1000 elements.

In [6]:
python_list = [5] * 1000
np_array = np.arange(1000)

%timeit np_array_squared = np_array ** 2 #%timeit mense meane of time in creating expression
%timeit python_list_squared = [x ** 2 for x in python_list]

1.66 µs ± 375 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
42.1 µs ± 1.89 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


There are some other convenient functions to create ndarray of different shapes and sizes.

In [7]:
# creates ndarray with 5 rows and 5 columns with all elements
# initialized to zero.
np.zeros((5, 5)) # Create a 5x5 array filled with zeros (default dtype: float)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
# similar to previous function, it also creates a ndarray of
# given dimension and initialize them to 1.
np.ones((5, 5))  # Create a 5x5 array filled with ones (default dtype: float)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Each ndarray has a shape property that returns a tuple containing the shape of the array. It also has a dtype property that returns the type of the data the ndarray contains. Finally, you can also use the ndim property to get the number of dimension of the ndarray.

In [9]:
print(array1d.shape)
print(array2d.shape)

(5,)
(3, 3)


In [10]:
print(array1d.dtype)
print(array2d.dtype)
print(array.dtype)

float64
float32
int16


In [11]:
#ndim is an attribute of a NumPy array. It tells you the number of dimensions of the array.
print(array1d.ndim)
print(array2d.ndim)

1
2


Other convenient functions to create a ndarray includes:

ones_like – creates an array of ones.

zeros_like – creates an array of zeros.

empty – creates an uninitialized array.

empty_like – creates an uninitialized array like another.

full – creates an array filled with a value.

full_like – creates a filled array like another.

eye – creates a 2D identity matrix.

identity – creates a square identity matrix.

It’s not safe to assume that numpy.empty will return an array of all zeros. This function returns uninitialized memory and thus may contain nonzero garbage values. You should use this function only if you intend to populate the new array with data.

In [12]:
# Creates a new array of the given size but does not populate them with
# any value.
empty_array = np.empty((5, 5))
empty_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# Creates a ndarray of the given size and fills them with the
# given value.
filled_array = np.full((5, 5), 3)
filled_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [14]:
# Returns a NxN identity matrix where the leading diagonal elements
# have the value of 1 and rests have 0.
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
# Creates a ndarray that has the shape of the empty_array created earlier
# and fills all the elements with 1.
np.ones_like(empty_array)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
# Creates a ndarray that has similar shape to array1d but
# fills each element with the integer 5.
np.full_like(array1d, 5)

array([5., 5., 5., 5., 5.])

In [17]:
# Creates a ndarray that has the shape of the empty_array created earlier
# and fills all the elements with 1.
np.ones_like(empty_array)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
# Creates a ndarray that has similar shape to array1d but
# fills each element with the integer 5.
np.full_like(array1d, 5)

array([5., 5., 5., 5., 5.])

# Changing Data Types

*   We can use the astype function to change between data types.
*   Calling astype always creates a new array (a copy of the data), even if the new dtype is the same as the old dtype.
*  If casting were to fail for some reason (like a string that cannot be converted to float64), a ValueError will be raised.







In [25]:
# different data types available in numpy
# np.sctypes  data types that are more specific than Python's built-in types

In [27]:
# Checks the inheritance hierarchy of int64
np.int64.mro() #Method Resolution Order

[numpy.int64,
 numpy.signedinteger,
 numpy.integer,
 numpy.number,
 numpy.generic,
 object]

We can use the astype function to cast any ndarray into another data type.

In [28]:
filled_array.astype(np.float64)

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [29]:
filled_array.astype(np.object_)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]], dtype=object)

In [30]:
filled_array.astype(np.bool_)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

If you cast some floating-point numbers to be of integer data type, the decimal part will be truncated.

In [31]:
arr = np.array([3.99, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

If you have an array of strings representing numbers, you can use astype to convert them to numeric form. Be cautious when using the numpy.string_ type, as string data in NumPy is fixed size and may truncate input without warning.

In [33]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.bytes_)
numeric_strings.astype(np.float32)

array([ 1.25, -9.6 , 42.  ], dtype=float32)

# Arithmetic With ndarray
Arrays are important because they enable you to express batch operations on data without writing any for loops. NumPy users call this vectorization. Arithmetic operation in NumPy is vectorized. It means that there is no need to write loops. For two similar sized ndarrays, any operation between them will be always elementwise.

In [34]:
array

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9],
      dtype=int16)

In [35]:
array2d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [41]:
array2 = np.arange(20, dtype=np.float64)
array2

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [43]:
array + 10

array([1010,   11,   12,   13,   14,   15,   16,   17,   18,   19],
      dtype=int16)

In [44]:
array2d - 1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]], dtype=float32)

In [45]:
array * 2

array([2000,    2,    4,    6,    8,   10,   12,   14,   16,   18],
      dtype=int16)

In [48]:
array ** 2

array([16960,     1,     4,     9,    16,    25,    36,    49,    64,
          81], dtype=int16)

In [49]:
1 / array2d

array([[1.        , 0.5       , 0.33333334],
       [0.25      , 0.2       , 0.16666667],
       [0.14285715, 0.125     , 0.11111111]], dtype=float32)

In [52]:
array4 = np.arange(10)
print(array4)
print(array)

[0 1 2 3 4 5 6 7 8 9]
[1000    1    2    3    4    5    6    7    8    9]


In [53]:
array + array4

array([1000,    2,    4,    6,    8,   10,   12,   14,   16,   18])

In [54]:
array - array4

array([1000,    0,    0,    0,    0,    0,    0,    0,    0,    0])

In [55]:
array * array4

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

Comparison between similar sized array yields boolean arrays.

In [56]:
array > array4

array([ True, False, False, False, False, False, False, False, False,
       False])

In [57]:
array < array4

array([False, False, False, False, False, False, False, False, False,
       False])

In [58]:
array == array4

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

# Broadcasting
Broadcasting is a mechanism that allows NumPy to perform arithmetic operations on arrays with different shapes. One of the simplest examples is when a scalar value is added to an ndarray—NumPy automatically extends the scalar across the entire array so the operation can be applied to each element.

In [59]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Below, the scalar value 10 has been broadcast to all the element of the array.

In [60]:
array + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Two arrays are compatible for broadcasting if for each trailing dimension (i.e., starting from the end) the axis lengths match or if either of the lengths is 1. Broadcasting is then performed over the missing or length 1 dimensions.

In [61]:
array1 = np.random.randn(4, 4)
print(array1)
print(array1.shape)

[[ 0.11579838 -0.9771112   1.39954034  2.9227857 ]
 [ 1.29835824 -1.8165827  -1.67107767 -0.7200089 ]
 [ 1.14174183  0.36749072  1.75066107  0.8878495 ]
 [-0.64530469  1.23825834 -0.38312003 -0.3683138 ]]
(4, 4)


In [62]:
array2 = np.random.randn(4, 1)
print(array2)
print(array2.shape)

[[ 0.57817724]
 [-0.8525016 ]
 [ 0.91165973]
 [-0.95199948]]
(4, 1)


In [63]:
array3 = np.random.randn(1, 4)
print(array3)
print(array3.shape)

[[ 1.24912938  1.48940127  0.90879828 -0.85560043]]
(1, 4)


In [64]:
array1 + array2

array([[ 0.69397562, -0.39893397,  1.97771758,  3.50096294],
       [ 0.44585665, -2.6690843 , -2.52357927, -1.5725105 ],
       [ 2.05340155,  1.27915045,  2.66232079,  1.79950922],
       [-1.59730417,  0.28625886, -1.33511951, -1.32031328]])

In [66]:
array1 - array3

array([[-1.133331  , -2.46651248,  0.49074206,  3.77838613],
       [ 0.04922886, -3.30598397, -2.57987595,  0.13559153],
       [-0.10738756, -1.12191055,  0.84186278,  1.74344993],
       [-1.89443407, -0.25114294, -1.29191831,  0.48728663]])

In [68]:
# Create a 3x5x5 array with random values (normal distribution)
array4 = np.random.randn(3, 5, 5)

# Create a 3x1x1 array with random values
# This will be broadcast across the last two dimensions
array5 = np.random.randn(3, 1, 1)

# Broadcasting happens here:
# array5 expands from (3,1,1) to (3,5,5) and is added element-wise to array4
array6 = array4 + array5

# Print the shape of the resulting array (expected: (3,5,5))
print(array6.shape)


(3, 5, 5)


# Indexing & Slicing
NumPy array indexing is a deep topic, as there are many ways you may want to select a subset of your data or individual elements.

In [69]:
array2d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [70]:
array2d[2, 1]

np.float32(8.0)

In [71]:
array2d[0]

array([1., 2., 3.], dtype=float32)

In [72]:
array2d[0, 0:2]

array([1., 2.], dtype=float32)

In [77]:
# Select all rows and only column index 2
array2d[0:, 2]

array([3., 6., 9.], dtype=float32)

In [84]:
array2d[1:, 1:]

array([[5., 6.],
       [8., 9.]], dtype=float32)

Sliced array returns a memory not a copy. So, be extra carefull while working with a sliced array.

In [87]:
sliced = array2d[0, :]
sliced

array([1., 2., 3.], dtype=float32)

In [88]:
sliced[0] = 1000
sliced

array([1000.,    2.,    3.], dtype=float32)

In [89]:
array2d

array([[1000.,    2.,    3.],
       [   4.,    5.,    6.],
       [   7.,    8.,    9.]], dtype=float32)

If you want a copy of a slice of an ndarray instead of a view, you will need to explicitly copy the array—for example, array2d[0, :].copy()

In [90]:
sliced = array2d[0, :].copy()
sliced

array([1000.,    2.,    3.], dtype=float32)

In [97]:
sliced[0] = 100
sliced

array([100.,   2.,   3.], dtype=float32)

In [98]:
print(array2d)
print(sliced)

[[1000.    2.    3.]
 [   4.    5.    6.]
 [   7.    8.    9.]]
[100.   2.   3.]


# Assignments
As you can see, if you assign a scalar value to a slice, as in array2d[0:1, 0:3] = 12, the value is propagated (or broadcast henceforth) to the entire selection.

In [108]:
array2d[0:1, 0:2] = [5, 4] #that mense first stape (row) start: stop & second stape (collumn)
array2d

array([[5., 4., 3.],
       [5., 5., 6.],
       [5., 5., 9.]], dtype=float32)

Boolean Indexing

In [115]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe'], dtype='<U4')

In [111]:
data = np.random.randn(6, 4)
data

array([[ 0.84328687, -0.34947939,  0.89649919,  0.52420756],
       [-0.82912657, -0.14761459, -1.18068284,  0.31496274],
       [ 2.10291076, -0.46590658,  0.38619435,  1.96007432],
       [-0.2307679 ,  0.81402415, -1.31191486,  0.91577921],
       [ 2.0930988 ,  1.0245267 , -0.80261725, -0.83323458],
       [ 1.44475021, -0.51648986, -1.08500304, -0.59122397]])

In [112]:
idx = (names == 'Bob')
idx

array([ True, False, False,  True, False, False, False])

In [113]:
names[idx]

array(['Bob', 'Bob'], dtype='<U4')

In [119]:
idx = (names != 'Bob')
idx

array([False,  True,  True, False,  True,  True])

In [120]:
names[idx]

array(['Joe', 'Will', 'Will', 'Joe'], dtype='<U4')

In [122]:
ask = (names == 'Bob') | (names == 'Will')
ask

array([ True, False,  True,  True,  True, False])

In [123]:
names[ask]

array(['Bob', 'Will', 'Bob', 'Will'], dtype='<U4')

In [124]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [126]:
a[a > 5]

array([6, 7, 8, 9])

# Facny Indexing

In [127]:
data

array([[ 0.84328687, -0.34947939,  0.89649919,  0.52420756],
       [-0.82912657, -0.14761459, -1.18068284,  0.31496274],
       [ 2.10291076, -0.46590658,  0.38619435,  1.96007432],
       [-0.2307679 ,  0.81402415, -1.31191486,  0.91577921],
       [ 2.0930988 ,  1.0245267 , -0.80261725, -0.83323458],
       [ 1.44475021, -0.51648986, -1.08500304, -0.59122397]])

In [128]:
data[0, 0]

np.float64(0.8432868675023664)

In [129]:
data[0][0]

np.float64(0.8432868675023664)

In [131]:
data[[0, 0, 1, 2, 3], [0, 1, 1, 2, 3]]

array([ 0.84328687, -0.34947939, -0.14761459,  0.38619435,  0.91577921])

data[[0, 0, 1, 2, 3], [0, 1, 1, 2, 3]]

# Reshape, Transpose, & Swap Axis

In [132]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
array.shape

(10,)

In [143]:
array.ndim

1

In [135]:
array.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [136]:
array.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [141]:
array.reshape(2, -1) # 2 → means we want the reshaped array to have 2 rows
                     # -1 → means NumPy will automatically calculate the number of columns
                     # based on the total number of elements in the array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [142]:
array.reshape(-1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [144]:
array2d


array([[5., 4., 3.],
       [5., 5., 6.],
       [5., 5., 9.]], dtype=float32)

In [147]:
array2d.T  # .T → stands for "transpose"
           #  It flips the array over its diagonal
           #  Rows become columns, and columns become rows


array([[5., 5., 5.],
       [4., 5., 5.],
       [3., 6., 9.]], dtype=float32)

In [148]:
array2d.swapaxes(1, 0)

array([[5., 5., 5.],
       [4., 5., 5.],
       [3., 6., 9.]], dtype=float32)

# Functions

In [149]:
array1d = np.arange(10)
print(array1d)

[0 1 2 3 4 5 6 7 8 9]


In [150]:
array2d = np.random.randn(5, 6)
print(array2d)

[[ 0.88503939  0.092146   -0.34028882 -0.39474471  1.16250825 -2.03176473]
 [-0.47722434  1.49456816  0.6985967  -1.48790959  1.10107686  1.43954642]
 [ 0.38018248  0.0838722   0.45179543 -0.6363819   0.97863677  1.00006527]
 [ 1.04536272 -0.90470198 -0.10496778  0.99508955 -0.30388218 -0.99127022]
 [-1.82137078 -1.46501853 -0.84425298 -1.41679213 -0.68459188  0.01234418]]


In [151]:
np.sqrt(array1d)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [152]:
np.sum(array1d)

np.int64(45)

In [153]:
np.sum(array2d, axis=0)

array([ 0.01198946, -0.69913414, -0.13911746, -2.94073878,  2.25374783,
       -0.57107908])

In [156]:
np.mean(array2d, axis=1)

array([-0.10451744,  0.46144237,  0.37636171, -0.04406165, -1.03661369])

In [157]:
np.var(array2d, axis=1)

array([1.07955925, 1.19507986, 0.31144099, 0.6626338 , 0.36752411])

In [158]:
np.std(array2d, axis=1)

array([1.0390184 , 1.09319708, 0.55806899, 0.81402322, 0.60623767])

In [159]:
np.quantile(array2d, .50, axis=0)

array([ 0.38018248,  0.0838722 , -0.10496778, -0.6363819 ,  0.97863677,
        0.01234418])

In [160]:
np.min(array2d, axis=0)

array([-1.82137078, -1.46501853, -0.84425298, -1.48790959, -0.68459188,
       -2.03176473])

In [161]:
np.max(array2d, axis=1)

array([1.16250825, 1.49456816, 1.00006527, 1.04536272, 0.01234418])

In [162]:
array1d.argmax()

np.int64(9)

In [163]:
array1d.max()

np.int64(9)

In [164]:
array2d.argmax(axis=0)

array([3, 1, 1, 3, 0, 1])

In [165]:
array1d.argmin()

np.int64(0)

In [167]:
np.cumsum(array1d) # cumsum → stands for "cumulative sum"

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [168]:
x = np.array([2, 3, 4, 5])
np.cumprod(x)

array([  2,   6,  24, 120])

In [169]:
array1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [170]:
array1d > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

# Linear Algebra

In [171]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [172]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [173]:
# Matrix Multiplication
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [174]:
# The @ operator is a shorthand for matrix multiplication
x @ y

array([[ 28.,  64.],
       [ 67., 181.]])

In [175]:
# The multiplication operator * yields elementwise multiplication
x * np.full_like(x, 2)

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

The numpy.linalg module contains all the industry standard functions for manipulating vectors and matrices. You can explore the available functions here.

In [176]:
from numpy import linalg

x = np.random.randn(5, 5)
x_inv = linalg.inv(x)
x

array([[ 0.26154651,  0.56747636, -0.93912819,  1.06876684,  1.17297728],
       [-0.30498922,  1.43961101, -0.14187336, -0.9410889 , -0.75826632],
       [-0.53999347,  1.62655065, -1.56625988, -1.36438226,  1.18004417],
       [ 0.74797343,  1.25935711,  0.7932418 ,  1.04341813,  1.44350582],
       [ 1.49840073, -0.20176038,  0.48772859,  1.00855058,  1.54100243]])

In [177]:
(x @ x_inv).astype(np.int16)

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1]], dtype=int16)

In [178]:
linalg.det(x)

np.float64(-9.815183830328223)

# File I/O
np.save and np.load are the two workhorse functions for efficiently saving and loading array data on disk. Arrays are saved by default in an uncompressed raw binary format with file extension .npy

In [179]:
x

array([[ 0.26154651,  0.56747636, -0.93912819,  1.06876684,  1.17297728],
       [-0.30498922,  1.43961101, -0.14187336, -0.9410889 , -0.75826632],
       [-0.53999347,  1.62655065, -1.56625988, -1.36438226,  1.18004417],
       [ 0.74797343,  1.25935711,  0.7932418 ,  1.04341813,  1.44350582],
       [ 1.49840073, -0.20176038,  0.48772859,  1.00855058,  1.54100243]])

In [180]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [191]:
import os
# Import the 'os' module to interact with the operating system
# It allows us to create directories, check files, etc.

if not os.path.exists('./Data'):
    # os.path.exists(path) → checks if the given path exists
    # './Data' → relative path for a folder named "Data"
    # 'not' → means if the folder DOES NOT exist, then do the next step

    os.makedirs('./Data')
    # os.makedirs(path) → creates a directory (or multiple directories if needed)
    # Here it creates a folder named "Data" in the current directory

np.save('./Data/matrix.npy', x)
# np.save(file, array) → saves a NumPy array to a file in .npy format
# './Data/matrix.npy' → the file path where the array will be saved
# x → the NumPy array to save
# Result: x is stored in "matrix.npy" inside the "Data" folder


In [192]:
loaded_data = np.load('./Data/matrix.npy')
loaded_data

array([[ 0.26154651,  0.56747636, -0.93912819,  1.06876684,  1.17297728],
       [-0.30498922,  1.43961101, -0.14187336, -0.9410889 , -0.75826632],
       [-0.53999347,  1.62655065, -1.56625988, -1.36438226,  1.18004417],
       [ 0.74797343,  1.25935711,  0.7932418 ,  1.04341813,  1.44350582],
       [ 1.49840073, -0.20176038,  0.48772859,  1.00855058,  1.54100243]])

In [193]:
np.savez('./Data/matrices.npz', matrix1 = x, matrix2 = y)

In [194]:
loaded_data = np.load('./Data/matrices.npz')

In [195]:
loaded_data['matrix1']

array([[ 0.26154651,  0.56747636, -0.93912819,  1.06876684,  1.17297728],
       [-0.30498922,  1.43961101, -0.14187336, -0.9410889 , -0.75826632],
       [-0.53999347,  1.62655065, -1.56625988, -1.36438226,  1.18004417],
       [ 0.74797343,  1.25935711,  0.7932418 ,  1.04341813,  1.44350582],
       [ 1.49840073, -0.20176038,  0.48772859,  1.00855058,  1.54100243]])

In [196]:
loaded_data['matrix2']

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])


# Reference
Chapter 4, McKinney, Wes. Python for data analysis: Data wrangling with Pandas, NumPy, and IPython. " O'Reilly Media, Inc.", 2012,
and sammak sir's notes.